### ISSUE TITLE
Proper Death Functionality

### ISSUE THREAD

**Issue by maluhia** [misternebula/quantum-space-buddies#235]
Please make it so if a character dies, it resets the loop for all! Teleporting back to Timber Hearth after flying into the sun is a tad underwhelming. Otherwise, give us the option to enable this functionality.

**Comment by misternebula** [comment]
Hi, we implemented the current death system as we thought making a player wait 22 minutes to respawn, or ending the loop for everyone, was unfair or not fun. Right now, i'm trying to add as much functionality as possible to make QSB playable and fun, and then I will go back and consider adding options for all the things we've decided on.
