### ISSUE TITLE
Orb Sync Bug

### ISSUE THREAD

**Issue by Krevace** [misternebula/quantum-space-buddies#243]
Whenever I interact with one of the Nomai control orbs, it falls out of its track, either floating or bouncing wildly in place. This makes opening any door to a Nomai ruin impossible.  

The console calls the following errors:

>InvalidOperationException: Operation is not valid due to the current state of the object. Stack trace: System.Linq.Enumerable.First[NomaiOrbTransformSync] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) System.Linq.Enumerable.First[NomaiOrbTransformSync] (IEnumerable`1 source, System.Func`2 predicate) QSB.OrbSync.Events.OrbUserEvent.HandleServer (QSB.WorldSync.Events.WorldObjectMessage message) QSB.OrbSync.Events.OrbUserEvent.OnReceiveLocal (Boolean server, QSB.WorldSync.Events.WorldObjectMessage message) QSB.Events.QSBEvent`1[T].OnReceive (Boolean isServer, .T message) QSB.Events.QSBEvent`1[T].<.ctor>b__5_0 (.T message) QSB.Messaging.MessageHandler`1[QSB.WorldSync.Events.WorldObjectMessage].OnClientReceiveMessageHandler (QuantumUNET.Messages.QSBNetworkMessage netMsg) QuantumUNET.QSBNetworkConnection.InvokeHandler (QuantumUNET.Messages.QSBNetworkMessage netMsg) QuantumUNET.QSBLocalClient.ProcessInternalMessages () QuantumUNET.QSBLocalClient.Update () QuantumUNET.QSBNetworkClient.UpdateClients () QuantumUNET.Components.QSBNetworkIdentity.UNetStaticUpdate () QSB.QSBCore.Update ()

>InvalidOperationException: Operation is not valid due to the current state of the object. Stack trace: System.Linq.Enumerable.First<QSB.OrbSync.QSBOrbSlot> (System.Collections.Generic.IEnumerable`1<QSB.OrbSync.QSBOrbSlot>,System.Func`2<QSB.OrbSync.QSBOrbSlot, bool>,System.Linq.Enumerable/Fallback) <0x001a9> System.Linq.Enumerable.First<QSB.OrbSync.QSBOrbSlot> (System.Collections.Generic.IEnumerable`1<QSB.OrbSync.QSBOrbSlot>,System.Func`2<QSB.OrbSync.QSBOrbSlot, bool>) <0x00061> QSB.WorldSync.QSBWorldSync.HandleSlotStateChange (NomaiInterfaceSlot,NomaiInterfaceOrb,bool) <0x00133> QSB.OrbSync.OrbPatches.CheckOrbCollision (bool&,NomaiInterfaceSlot,NomaiInterfaceOrb,bool,single,single,NomaiInterfaceOrb&) <0x002ce> (wrapper dynamic-method) NomaiInterfaceSlot.CheckOrbCollision_Patch1 (object,NomaiInterfaceOrb) <0x0007a> NomaiInterfaceOrb.CheckSlotCollision (bool) <0x0023d> NomaiInterfaceOrb.FixedUpdate () <0x00645>

**Comment by misternebula** [comment]
Can you give more information on when this occurs?
