### ISSUE TITLE
Feature Request: Compataibility with NomaiVR

### ISSUE THREAD

**Issue by JpTiger** [misternebula/quantum-space-buddies#246]
It would be absolutely incredible to play this multiplayer in VR. Any chance we could collaborate with the mods? They're both pretty extensive, I imagine.

**Comment by JpTiger** [comment]
Just to get folks on the same page, potentially: https://github.com/Raicuparta/nomai-vr/issues/383

**Comment by misternebula** [comment]
Raicuparta summed it up pretty well in https://github.com/Raicuparta/nomai-vr/issues/383#issuecomment-778169165
But in short :
- NomaiVR is no longer being actively developed.
- Both mods modify huge parts of the game in different ways.
- Making QSB work by itself is hard enough, let alone trying to track and sync everything that VR entails.
While the idea is not "never going to happen", it's more than likely that it won't. Definitely not until QSB is feature-complete, which it might never be.
