### ISSUE TITLE
"NoResources" spam???

### ISSUE THREAD

**Issue by misternebula** [misternebula/quantum-space-buddies#320]

**Comment by JohnCorby** [comment]
i have never seen this happen once

**Comment by AsterAether** [comment]
Can kinda confirm that that happens? Had these NoResources messages when playing as host. Other player could not see me move, but I could see the other player moving. I have a pretty weak upload, maybe that is part of the problem?
Can create a more detailed report around the Weekend when we get to play again ^^

**Comment by AsterAether** [comment]
Ok Update:
Had the opportunity to test again, it worked once out of 6 tries. All the other tries ended with these messages getting spammed:
```
Send Error: NoResources channel:1 bytesToSend:80
[OWML.Unity] : Failed to send internal buffer channel:1 bytesToSend:80
```
over and over when I (the host) tried to move. I could see the other player just fine though.

**Comment by misternebula** [comment]
Interesting. Does this happen every time you play?

**Comment by AsterAether** [comment]
Sadly no, and it seems to have gone away entirely now, so I can't reproduce it. My hypothesis is that it had something to do with bandwidth, as that day I had really bad internet.

**Comment by misternebula** [comment]
Most likely to do with bad internet connection, which is out of our control.
Also haven't seen this in ages. Closing.
