### ISSUE TITLE
Quantum Space Buddies does not initialize correctly on game start

### ISSUE THREAD

**Issue by conjohnerton** [misternebula/quantum-space-buddies#330]
**Describe the bug**
I noticed that the QSB menu did not show at the top of the screen. I then checked the logs in OMWL and got this error: ```Error while adding/initializing Raicuparta.QuantumSpaceBuddies: System.NullReferenceException: Object reference not set to an instance of an object at OWML.ModLoader.Owo.InitializeMod (System.Type modType, OWML.Common.IModHelper helper) [0x0008a] in <14a0e1e29d7b47898d5ec7f3b0893ad4>:0```.

**To Reproduce**
Update to latest version of QSB. (v0.12.1) and run the game through the OWML.

**Expected behavior**
Connect menu pops up on the top left.

**Please complete the following information:**
 - OS : Windows 10
 - Outer Wilds version : v1.1.10
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : 0.12.1

**Comment by misternebula** [comment]
Hi!
This seems more like an OWML issue. We've heard some people getting this before, but very rarely.

Try :
- Reinstalling QSB
- Reinstalling OWML
- Verifying game files

I'll open an issue on the OWML repo so we can take a further look at this.

**Comment by misternebula** [comment]
Closing as this is an OWML issue.
