### ISSUE TITLE
Singularity shader sometimes dissapears.

### ISSUE THREAD

**Issue by misternebula** [misternebula/quantum-space-buddies#343]
**Describe the bug**
The singularity shader (black/white holes, probe recall effect, etc) sometimes is invisible.

**To Reproduce**
Who knows???

**Expected behavior**
This shouldn't happen.

**Please complete the following information:**
 - OS : Windows
 - Outer Wilds version : 1.1.11.72
 - Outer Wilds vendor (Steam/Epic) : Epic
 - QSB Version : Dev, but found in previous (non dev) versions as well.

**Additional context**
What the fuck.

**Comment by JohnCorby** [comment]
what the fuck

**Comment by misternebula** [comment]
Haven't seen this recently, closing.
