### ISSUE TITLE
Respawn not working

### ISSUE THREAD

**Issue by MBrinks2239** [misternebula/quantum-space-buddies#351]
**Describe the bug**
After dying, you will enter the map that you cannot exit. This can only be resolved by the other player committing suicide. After which a new loop will begin. In the new loop you cannot open the map.

**To Reproduce**
*(Unexitable map steps)*
* Enter game with friend.
* Kill self at fire.
* Get stuck at map.

*(Not working map steps)*
* Other player kills self. (Most consistent when flying into the sun or hollows lantern)
* Loop restarts.
* Cannot open map.

**Expected behavior**
After dying, I expect to be respawned at timber heart and regain control of my character.
After the loop reset, I expect to be able to use the map.

**Please complete the following information:**
 - OS : Host: windows 11, Client: windows 10
 - Outer Wilds version : 1.1.10.47 and 1.1.11 (Tried both with and without dlc installed)
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : 0.12.2

**Additional context**
Only the player that died first. (And thus gets stuck at the non exitable map) Is unable to open his map for any future loop without a restart. If the other player dies first, both players will be unable to use their maps.

An amazing mod! Keep up the great work!

![doggo-dog](https://user-images.githubusercontent.com/44466724/142057432-72190135-b21a-41d0-9b6c-8eadf41c0539.gif)

**Comment by misternebula** [comment]
Yeah, this is my fault. I haven't put any writing on how the respawn system actually works... and I don't really know how to.

When you die, you enter that map. Someone else then has to go to the ship, go to the refill point (where you get health/fuel), and press "Respawn Player"

I could just write this into the readme, or have a marker in game? Not sure.

That second bit, where you can't open your map in future maps, is a bug though. I'll look into it.
