### ISSUE TITLE
Quantum moon quantum objects are wack

### ISSUE THREAD

**Issue by misternebula** [misternebula/quantum-space-buddies#381]
**Describe the bug**
Going in and out of the QM results in weird quantum object ownership.

**To Reproduce**
Unknown

**Expected behavior**
When no one is in the QM, the objects should be owned by no-one.

**Screenshots**
![image](https://user-images.githubusercontent.com/41904486/144203265-2b1cdeba-4d75-40d4-9678-b1b0ea98d127.png)

**Please complete the following information:**
 - OS : Windows 10
 - Outer Wilds version : 1.1.11.72
 - Outer Wilds vendor (Steam/Epic) : Epic
 - QSB Version : dev

**Comment by JohnCorby** [comment]
does #385 fix this?
