### ISSUE TITLE
Shuttle orbs don't do anything when not in the shuttle

### ISSUE THREAD

**Issue by misternebula** [misternebula/quantum-space-buddies#420]
**Describe the bug**
A shuttles controls does not do anything if the local player is not in the shuttle.

**To Reproduce**
Have both people in a shuttle.
Launch shuttle.
Land shuttle.
Have one person get out of the shuttle and step back.
Have the other player warp the shuttle back.

**Expected behavior**
The shuttle should warp back even if the local player isn't inside it

**Comment by JohnCorby** [comment]
fixed #415
