### ISSUE TITLE
Loss of save for the second player.

### ISSUE THREAD

**Issue by Kamelblua** [misternebula/quantum-space-buddies#454]
**Describe the bug**
Loss of progress on the rumors of the player who leaves the server.

**To Reproduce**
When the second player leaves the host server and when he rejoins he loses all rumors.

**Expected behavior**
I would like the player to keep the progress after leaving the server to continue where we left off, please.

**Screenshots**
In the rumor panel, he just has the village map.

**Please complete the following information:**
 - OS : Windows 10
 - Outer Wilds version : The last
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : 14.1

**Additional context**
But the host does not lose its progression, unless it joins another server.

**Comment by misternebula** [comment]
This will be fixed in #433

**Comment by Kamelblua** [comment]
okok, thanks for the correction, and your work on this mod :)
