### ISSUE TITLE
Ship scout recovery & eject button do not work after selecting "open to multiplayer"

### ISSUE THREAD

**Issue by ianklatzco** [misternebula/quantum-space-buddies#471]
**Describe the bug**
When host, and the only player connected, retrieving the ship scout and pushing the eject button do not work.

**To Reproduce**
- Get in ship
- Scout: 
    - Fire scout
    - Attempt to recall scout
    - Scout keeps flying. A buggy recover sound effect plays.
 - Eject button
    - Attempt to push.
    - Nothing happens.

**Please complete the following information:**
 - OS : Windows 11
 - Outer Wilds version : 1.1.12
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : 0.15.1

**Additional context**
The eject button does not produce any logs.

Logs from recovering scout launcher:
```
Error - WorldObjectsToUnityObjects does not contain "ProbeLauncher"! TWorldObject:QSBProbeLauncher, TUnityObject:PlayerProbeLauncher, Stacktrace:at System.Environment.get_StackTrace () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0at QSB.WorldSync.QSBWorldSync.GetWorldObject[TWorldObject] (UnityEngine.MonoBehaviour unityObject) [0x00000] in <a5264eee4ec642b9ae9e73ad2d5c2c16>:0at QSB.Tools.ProbeLauncherTool.Patches.LauncherPatches.ProbeLauncher_RetrieveProbe (ProbeLauncher __instance, System.Boolean playEffects, System.Boolean forcedRetrieval) [0x00000] in <a5264eee4ec642b9ae9e73ad2d5c2c16>:0at ProbeLauncher.DMD<ProbeLauncher::RetrieveProbe> (ProbeLauncher , System.Boolean , System.Boolean ) [0x00000] in <6981773f82a4486a9b48d7b04937b6e2>:0at ProbeLauncher.UpdatePostLaunch () [0x00000] in <6981773f82a4486a9b48d7b04937b6e2>:0at ProbeLauncher.Update () [0x00000] in <6981773f82a4486a9b48d7b04937b6e2>:0 | Quantum Space Buddies |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: QSB.Messaging.QSBMessageManager.SendMessage[T,M] (T worldObject, M msg) (at <a5264eee4ec642b9ae9e73ad2d5c2c16>:0)QSB.Tools.ProbeLauncherTool.Patches.LauncherPatches.ProbeLauncher_RetrieveProbe (ProbeLauncher __instance, System.Boolean playEffects, System.Boolean forcedRetrieval) (at <a5264eee4ec642b9ae9e73ad2d5c2c16>:0)(wrapper dynamic-method) ProbeLauncher.DMD<ProbeLauncher::RetrieveProbe>(ProbeLauncher,bool,bool)ProbeLauncher.UpdatePostLaunch () (at <6981773f82a4486a9b48d7b04937b6e2>:0)ProbeLauncher.Update () (at <6981773f82a4486a9b48d7b04937b6e2>:0) | OWML
```
(same log as photo for better readability)
![image](https://user-images.githubusercontent.com/1487413/151334541-3a03067a-c0db-4bab-a906-1f1231996caa.png)

**Comment by misternebula** [comment]
Hi!
The eject button not working is intentional. Having the ship break into pieces is (right now) not something we can handle.
The ship scout launcher bug has been identified, and a fix exists on our dev branch.

**Comment by ianklatzco** [comment]
thanks for the great mod! 🙏
