### ISSUE TITLE
Artifact is visible through the walls

### ISSUE THREAD

**Issue by Tllya** [misternebula/quantum-space-buddies#502]
**Describe the bug**
Artifact is visible through the walls.

**To Reproduce**
Take the artifact
The other player must go behind the wall
The artifact is still visible

**Expected behavior**
The artifact should not be seen through walls

**Screenshots**
![unknown](https://user-images.githubusercontent.com/94857119/159917839-9615ae52-c93b-49cd-ac39-5870c7fff5b5.png)

**Please complete the following information:**
 - OS : Windows
 - Outer Wilds version : 1.1.12
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : dev(0.18.0)

**Additional context**
The artifact can only be seen through walls if the player is holding it

**Comment by JohnCorby** [comment]
definitely possible to fix, just annoying and im lazy and its not a big priority
