### ISSUE TITLE
Jellfish yeeted (yote?) player out of solar system

### ISSUE THREAD

**Issue by misternebula** [misternebula/quantum-space-buddies#547]
https://v.redd.it/9v1736vwwkf91/DASH_1080.mp4?source=fallback

This is a bug for you, @JohnCorby :)

**Comment by JohnCorby** [comment]
that's hilarious i ain't fixing that

**Comment by misternebula** [comment]
Another person has reported this.

**Comment by misternebula** [comment]
Reproduction steps : (Exaggerated by speeding up jellyfish acceleration by 10x)
- Player A enters jellyfish domain.
- Player B enters jellyfish domain.
- Player A enters jellyfish.
- Player B enters/goes near jellyfish.
- Player A's GD gets fucked up (resulting in being yeeted)
