### ISSUE TITLE
Version 0.21.0 Breaks Gamepass

### ISSUE THREAD

**Issue by petersm8** [misternebula/quantum-space-buddies#558]
Menu broke for friend after updating to .21.0.
Was unable to click on any of the menu items.
A rollback to .20.2 fixed the issue.

**Comment by misternebula** [comment]
Unfortunately, I don't have gamepass. So I can't test anything on it... Can you post the game logs?

**Comment by misternebula** [comment]
Just bought gamepass for one month to try and fix this.
