### ISSUE TITLE
Client connects to singleplayer game instead of host game.

### ISSUE THREAD

**Issue by planksteak** [misternebula/quantum-space-buddies#583]
**Describe the bug**
Sometimes, when the client fails to connect to the host, (I think when the host leaves whilst the client is connecting) the client will be put into a single-player game instead. The notification for "Client disconnected with error" still appears as you go into the game.

**To Reproduce**
1- Get a host to host and a player to connect.
2- Get the host to disconnect from the game whilst the player is connecting.

**Expected behavior**
The player should be put into a singleplayer game.

**Please complete the following information:**
 - OS : Windows 10
 - Outer Wilds version : Newest
 - Outer Wilds vendor (Steam/Epic) : Steam
 - QSB Version : 0.22.0

**Comment by misternebula** [comment]
You say the expected behaviour is "The player should be put into a singleplayer game.", but is this not the issue you are reporting?

**Comment by misternebula** [comment]
This issue is kinda not fixable, since the game scene is loaded async. It's not possible to cancel an async scene load.
