### ISSUE TITLE
Can't respawn on death.

### ISSUE THREAD

**Issue by ghosterfox** [misternebula/quantum-space-buddies#593]
I died in the ship and got crushed by a platform and I couldn't respawn. Then when my friend died also we were just stuck in the map.

**Comment by ghosterfox** [comment]
Happened again when I talked to gabbro and meditated.

**Comment by misternebula** [comment]
This should be fixed with the latest release. Please re-test.

**Comment by misternebula** [comment]
Closing since this is assumed to be fixed.
