### ISSUE TITLE
can't connect to my friend's lobby

### ISSUE THREAD

**Issue by SantoneSgravato** [misternebula/quantum-space-buddies#628]
hi!
sorry for my english, not my main language. when i try connecting to my friend world, i get the "client disconnetted with error" message, played the mod one month ago and was working for all of us. we are 4 and we can't connect to each other even trying different host
this is the log when i try to connect:

<html>
<body>

Started console server on port 59505 | Mod Manager |  
-- | -- | --
Client connected to console | Mod Manager |  
Started OWML v2.9.0 | OWML |  
Game found in D:/SteamLibrary/steamapps/common/Outer Wilds | OWML |  
Game version: 1.1.13.456 | OWML |  
Game files copied. | OWML |  
Found mods: | OWML |  
* JohnCorby.VanillaFix v0.12.0 | OWML |  
* Raicuparta.QuantumSpaceBuddies v0.28.0 | OWML |  
* _nebula.MenuFramework v3.0.0 | OWML |  
Copying OWML files... | OWML |  
Copying replacement OW files... | OWML |  
Patching OW assembly... | OWML |  
- Assembly is already patched. | OWML |  
Updating incremental GC... | OWML |  
Identified as a Steam install. Launching... | OWML |  
Client disconnected from console | Mod Manager |  
Client connected to console | Mod Manager |  
Mod loader has been initialized. | OWML |  
Game version: 1.1.13.456 | OWML |  
Initializing enum creator | OWML |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\_nebula.MenuFramework\assets/menuframework | Menu Framework |  
* Start of QSB version 0.28.0 - authored by Nebula, John, Alek, & Rai | Quantum Space Buddies |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_network | Quantum Space Buddies |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_conversation | Quantum Space Buddies |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_debug | Quantum Space Buddies |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_hud | Quantum Space Buddies |  
Error - Could not find translation for language ITALIAN! Defaulting to English. | Quantum Space Buddies |  
Epic Manager: Category - LogEOSConnect Message - DeviceId access credentials already exist for the current user profile on the local device. | OWML |  
Loading asset bundle from C:/Users/santo/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_empty | Quantum Space Buddies | 14
Could not find multiplayer game save for paolo | OWML |  
Error - Could not find translation for language ITALIAN! Defaulting to English. | Quantum Space Buddies | 3
Disconnecting from server... | Quantum Space Buddies |  
Exception: Connection closed: The connection was gracefully closed by remote user.Stacktrace: EpicTransport.Common.OnConnectFail (Epic.OnlineServices.P2P.OnRemoteConnectionClosedInfo result) (at <bc7c91e4a47b44078ef8f7e930de4761>:0)Epic.OnlineServices.P2P.P2PInterface.OnRemoteConnectionClosedCallbackInternalImplementation (System.IntPtr data) (at <69370dce6f6442a8bae0d095baab8e71>:0)Epic.OnlineServices.Platform.PlatformInterface.Tick () (at <69370dce6f6442a8bae0d095baab8e71>:0)EpicTransport.EOSSDKComponent.Tick () (at <bc7c91e4a47b44078ef8f7e930de4761>:0)EpicTransport.EosTransport.ServerEarlyUpdate () (at <bc7c91e4a47b44078ef8f7e930de4761>:0)Mirror.NetworkServer.NetworkEarlyUpdate () (at <ff7833e2e1b74f6b97cfffca9074c9f9>:0)Mirror.NetworkLoop.NetworkEarlyUpdate () (at <ff7833e2e1b74f6b97cfffca9074c9f9>:0) | OWML |  
Connection to 00023a4bedad43b0ab4e19a867603420 timed out. | OWML |  
Object reference not set to an instance of an object | OWML |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: EpicTransport.Client+<>c__DisplayClass29_0.<CreateClient>b__1 () (at <bc7c91e4a47b44078ef8f7e930de4761>:0)EpicTransport.Client.OnConnectionFailed (Epic.OnlineServices.ProductUserId remoteId) (at <bc7c91e4a47b44078ef8f7e930de4761>:0)EpicTransport.Client+<Connect>d__30.MoveNext () (at <bc7c91e4a47b44078ef8f7e930de4761>:0)--- End of stack trace from previous location where exception was thrown ---System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <85d1d3e7744a4a47b5f51883bf40bba2>:0)UnityEngine.UnitySynchronizationContext:ExecuteTasks() | OWML |  
Epic Manager: Category - LogEOSMessaging Message - Stomp message failed. LocalUserId=[000...e9c] Topic=[/1f164829371e4cdcb23efedce98d99ad/account/00023a4bedad43b0ab4e19a867603420] Error=[Request timed out] | OWML | 10
Error - Could not find translation for language ITALIAN! Defaulting to English. | Quantum Space Buddies |  
Connection to 00023a4bedad43b0ab4e19a867603420 timed out. | OWML |  
Disconnecting from server...

</body>
</html>

this is the log of the host:
Started console server on port 54498 Mod Manager     Client connected to console Mod Manager     Started OWML v2.9.0 OWML     Game found in C:/Program Files (x86)/Steam/steamapps/common/Outer Wilds OWML     Game version: 1.1.13.456 OWML     Game files copied. OWML     Found mods: OWML     * JohnCorby.VanillaFix v0.12.0 OWML     * Raicuparta.QuantumSpaceBuddies v0.28.0 OWML     * _nebula.MenuFramework v3.0.0 OWML     Copying OWML files... OWML     Copying replacement OW files... OWML     Patching OW assembly... OWML     - Assembly is already patched. OWML     Updating incremental GC... OWML     Identified as a Steam install. Launching... OWML     Client disconnected from console Mod Manager     Client connected to console Mod Manager     Mod loader has been initialized. OWML     Game version: 1.1.13.456 OWML     Initializing enum creator OWML     Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods_nebula.MenuFramework\assets/menuframework Menu Framework     * Start of QSB version 0.28.0 - authored by Nebula, John
Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_network
Quantum Space Buddies
Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_conversation
Quantum Space Buddies
Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_debug
Quantum Space Buddies
Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_hud
Quantum Space Buddies
Error - Could not find translation for language ITALIAN! Defaulting to English.
Quantum Space Buddies
Epic Manager: Category - LogEOSConnect Message - DeviceId access credentials already exist for the current user profile on the local device.
OWML
Loading asset bundle from C:/Users/Utente/AppData/Roaming/OuterWildsModManager/OWML/Mods\Raicuparta.QuantumSpaceBuddies\AssetBundles/qsb_empty
Quantum Space Buddies    14
Could not find multiplayer game save for Mario
OWML
Error - Could not find translation for language ITALIAN! Defaulting to English.
Quantum Space Buddies    2
OWMenuInputModule send CANCEL!
OWML    2
Error - Could not find translation for language ITALIAN! Defaulting to English.
Quantum Space Buddies
Warning - Tried to send message QSB.Player.Messages.RequestStateResyncMessage before local player was established.
Quantum Space Buddies
Warning - ServerLoopCount is not the same as local loop count! local:121 server:0
Quantum Space Buddies 
Error - Tried to run OnUniverseSceneLoaded when PlayerTransformSync.LocalInstance was null!
Quantum Space Buddies
Error - Tried to init when PlayerTransformSync.LocalInstance was null!
Quantum Space Buddies
Warning - ServerStateManager.Instance is null!
Quantum Space Buddies
Warning - Tried to build WorldObjects when LocalPlayer is not ready! Building when ready...
Quantum Space Buddies
Warning - Tried to unpatch type RespawnTime, when it is either unpatched or was never patched.
Quantum Space Buddies
Error - LocalPlayer.Camera is null.
Quantum Space Buddies
Warning - Could not find any players with cameras!

thanks!

**Comment by JohnCorby** [comment]
epic transport being goofy again, see the [FAQ section](https://github.com/misternebula/quantum-space-buddies#i-keep-timing-out-when-trying-to-connect)
