### ISSUE TITLE
Option to disable the Chat functionality

### ISSUE THREAD

**Issue by Tek-03** [misternebula/quantum-space-buddies#629]
**Is your feature request related to a problem? Please describe.**
Me and a friend are able to get NomaiVR working with QSB without major issue. However, when we wear our space suits, the chat function prevents us from playing the game, piloting, or exiting the ship

**Describe the solution you'd like**
Can you include an option to disable the chat functionality, and still allow us to not use KCP Transport?

**Describe alternatives you've considered**
Check for NomaiVR, and disable the chat functionality automatically.
Is it possible to disable KCP transport in an older version of QSB?

**Additional context**
I completely understand that it is no longer a priority for you to maintain compatibility for VR... But we're _SO CLOSE!!_ My BF's ISP will not allow them to open the port 7777, so going to an older version will not work.

Thank you!

**Comment by AlexSchweighofer** [comment]
Yes pleas! It would be perfect with just that, or at least if you could tell us a workaround!

**Comment by Rookie056** [comment]
I had the same exact experience. It seems to take precedence over the general interact key on nomai vr. either disabling chat or finding some way to add a keybind could work.
