### ISSUE TITLE
Eye: Fix suit sync

### ISSUE THREAD

**Issue by Raicuparta** [misternebula/quantum-space-buddies#81]
When arriving at the eye, suit is equipped by default. Since no "suit up" event happened, players don't see each other with suit equipped until suit state changes.

**Comment by misternebula** [comment]
VesselWarpController does send a suitup message though. So something else is broken.

```
if (this._instantlyPutOnSuit && !Locator.GetPlayerSuit().IsWearingSuit(true))
{
        Locator.GetPlayerSuit().SuitUp(false, true);
	this._instantlyPutOnSuit = false;
}
```

**Comment by Raicuparta** [comment]
Probably because when one player sends the suit up message, the other hasn't arrived on the scene yet, so they can't trigger the suit toggle. This gets fixed with the "global state" stuff that we talked about. Global state would say "player A is wearing suit", player B joins, reads global state, updates its own game.

**Comment by misternebula** [comment]
should be fixed indirectly by the animation update in this PR

**Comment by misternebula** [comment]
nevermind
